name: Fetch RSS Feed

on:
  schedule:
    # Runs every day at 12:00 UTC
    - cron: '0 12 * * *'

jobs:
  fetch-rss:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Fetch RSS Feed and Write to File
      run: |
        pip install requests
        python ./fetch_rss.py

    - name: Commit and push if there are changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/agg-mb/cvepublication.git
        git add -A
        git diff --quiet && git diff --staged --quiet || git commit -m "Update RSS Feed data"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
